name: Release Alpha

on:
  workflow_dispatch:
    inputs:
      version_scale:
        description: Version scale
        required: true
        type: choice
        default: "patch"
        options:
        - "minor"
        - "major"
        - "patch"

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - uses: actions/checkout@v2
      - name: Configure Git User
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
      - name: Use Node.js 14.x
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"
          registry-url: https://registry.npmjs.org
      - name: Release
        run: npm run release-alpha
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_PUBLISH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
          RELEASE_SCALE: ${{ github.event.inputs.version_scale }}
